image: bioconductor/bioconductor_full:release

stages:
  - build
  - vignette
  - check
#  - document
#  - check
#  - test
#  - deploy

variables:
  _R_CHECK_CRAN_INCOMING_: "false"
  _R_CHECK_FORCE_SUGGESTS_: "true"

before_script:
  - R -e "install.packages(c('devtools'))"

build_binary:
  stage: build
  script:
    - R -e 'devtools::build(binary = TRUE, vignette = FALSE)'

build_source:
  stage: build
  script:
    - R -e 'devtools::build(binary = FALSE, vignette = FALSE)'

compile_vignette:
  stage: vignette
  script:
    - R -e 'devtools::build_vignettes()'

check_package:
  stage: check
  script:
    - R -e 'devtools::check(".", args = "--no-vignettes")'
