#image: bioconductor/bioconductor_full:release
image: rocker/tidyverse:3.6.1

stages:
  - dependencies
  - check
  - vignette
  - codecov
  - build
  - deploy

variables:
  _R_CHECK_CRAN_INCOMING_: "false"
  _R_CHECK_FORCE_SUGGESTS_: "true"

before_script:
  - echo "options('repos' = 'https://ftp.fau.de/cran/')" >> /usr/local/lib/R/etc/Rprofile.site
  #- R -e "install.packages(c('devtools'))"

install_dependencies:
  stage: dependencies
  script:
    - R -e "devtools::install_deps(pkg = '.', upgrade = 'always')"

check_package:
  stage: check
  script:
    - R -e "devtools::check(pkg = '.', args = '--no-vignettes', check_dir = '.')"
  artifacts:
    paths:
      - "*.Rcheck"
    name: logs
    when: always

#check_errors:
#  stage: check
#  script:
#    - R -e "if (!identical(devtools::check(pkg = '.', document = FALSE, args = c('--no-tests', '--no-vignettes'))[['errors']], character(0))) stop('Check with Errors')"

#check_warnings:
#  stage: check
#  script:
#    - R -e "if (!identical(devtools::check(pkg = '.', document = FALSE, args = c('--no-tests', '--no-vignettes')))[['warnings']], character(0))) stop('Check with Warnings')"

#check_notes:
#  stage: check
#  script:
#    - R -e "if (!identical(devtools::check(pkg = '.', document = FALSE, args = c('--no-tests', '--no-vignettes')))[['notes']], character(0))) stop('Check with Notes')"

compile_vignette:
  stage: vignette
  script:
    - R -e "devtools::build_vignettes(pkg = '.')"
  artifacts:
    paths:
      - "vignettes/sigident-Howto_Microarray.HTML"

codecoverage:
  stage: codecov
  script:
    - R -e 'covr::codecov()'

build_source:
  stage: build
  script:
    - R -e "devtools::build(pkg = '.', binary = FALSE, vignette = FALSE)"

build_binary:
  stage: build
  script:
    - R -e "devtools::build(pkg = '.',binary = TRUE, vignette = FALSE)"

install:
  stage: deploy
  script:
    - r -e 'devtools::install()'
