image: bioconductor/bioconductor_full:release

stages:
  - dependencies
  - check
  - vignette
  - build
#  - document
#  - check
#  - test
#  - deploy

variables:
  _R_CHECK_CRAN_INCOMING_: "false"
  _R_CHECK_FORCE_SUGGESTS_: "true"

before_script:
  - echo "options('repos' = 'https://ftp.fau.de/cran/')" >> /usr/local/lib/R/etc/Rprofile.site
  - R -e "install.packages(c('devtools'))"

#build_binary:
#  stage: build
#  script:
#    - R -e "devtools::build(binary = TRUE, vignette = FALSE)"

install_dependencies:
  stage: dependencies
  script:
    - R -e "devtools::install_deps(pkg = '.', upgrade = 'always')""

check_package:
  stage: check
  script:
    - R -e "devtools::check(pkg = '.', args = '--no-vignettes')"

compile_vignette:
  stage: vignette
  script:
    - R -e "devtools::build_vignettes(pkg = '.')"

build_source:
  stage: build
  script:
    - R -e "devtools::build(pkg = '.', binary = FALSE, vignette = FALSE)"
